### ISSUE TITLE
Largest scrollable element detection breaks in background tabs (and more)

### ISSUE THREAD

**Issue by abastardi** [akhodakivskiy/VimFx#605]
The fix from [this commit](https://github.com/akhodakivskiy/VimFx/commit/007cdb61523e01b6b9e317d1cdb91e839ba437c8) has had no effect in Gmail or Google Groups.

**Comment by lydell** [comment]
Works for me.

... except that if I first visit https://groups.google.com/forum/#!overview and then click a link to a group, the list of posts in that group is not automatically scrollable.

**Comment by abastardi** [comment]
It definitely does not work at all for me. Any ideas on how I can help debug to figure out the difference between my machine and yours?

Also, when I use f or zf, I do not see any hints that can be used to focus any scrollable areas (in Gmail, Google Groups, or any website). Of course, there are hints for links *within* scrollable areas, but no hint specifically to activate the scrollable area itself. Can you show a screenshot of an example where there is a hint to focus a scrollable area (e.g., in Google Groups)?

Thank you.

**Comment by lydell** [comment]
Just noticed that in the case I described where a list didn’t get automatically scrollable, if I use Google Group’s shortcut `f`, which hides the scrollbar, the list gets automatically scrollable.

----

Here’s a screenshot of the hints on Google Groups. The hint for the scrollable element is “F” (which I’ve marked with an extremely ugly red arrow).

![gg](https://cloud.githubusercontent.com/assets/2142817/11131836/e0e6d650-898c-11e5-8879-ba573d21f853.png)

**Comment by lydell** [comment]
Perhaps we should style the hints for scrollable elements differently so it’s easier to find them in crowded places such as on groups.google.com.

> Any ideas on how I can help debug to figure out the difference between my machine and yours?

Well, you could start by trying in a clean profile.

**Comment by abastardi** [comment]
OK, I have tried it with a totally clean Firefox profile and still observe the same problems -- scrolling does not work, and no hint is produced for scrollable areas when hitting `f` or `zf`. However, there are some nuances as well as differences between Gmail and Google Groups:

 1. In no circumstances can I get scrolling to work in Google Groups without using `f` to first explicitly focus the scrollable area.

 2. Both scrolling and the scrollable area hint are broken on both Gmail and Google Groups whenever they load in a background tab. Loading in a background tab happens in multiple circumstances, including (a) any non-foreground *pinned* tabs upon Firefox restart, (b) any non-foreground *non-pinned* tabs upon Firefox restart if the "Don't load tabs until selected" option is unchecked, (c) opening a link in a new background tab (e.g., via `F`), and (d) duplicating a page with `yt`. If you switch to a Gmail or Google Groups tab that has been loaded in the background, scrolling will not work, nor will a hint appear for the scrollable area when hitting `f`.

 3. If Gmail loads in the foreground, then both scrolling and the scrollable area hint work. Loading in the foreground includes (a) Gmail being the foreground tab upon Firefox startup, (b) hitting reload on a Gmail tab that had originally been loaded in the background, (c) opening a link in a new foreground tab (e.g., via `gf`), and (d) creating a new blank tab and enter Gmail in the address bar.

    I have noticed, though, that once I get scrolling to work in a Gmail tab, sometimes when I leave the tab and later return, scrolling has stopped working and I have to reload again to get it back.

 4. As noted above, even when loading/reloading Google Groups in the foreground, scrolling still does not work. However, loading in the foreground does enable the scrollable area hint to appear when pressing `f` or `zf`.

In short, (a) everything works in Gmail, but only if loaded/reloaded in the foreground, and (b) in Google Groups, scrolling never works, but the scrollable area hint does work when loaded/reloaded in the foreground.

For another example, Slack behaves exactly the same as Gmail (i.e., works only when loaded in the foreground).

One other thing I notice -- when hitting `j`/`k` on Google Groups, the whole page does bump up and down a couple pixels, as if the page is slightly larger than the viewport. If I zoom out far enough, that slight movement goes away, but even at that point, scrolling still does not work.

Anything else I can do to help diagnose?

What about alternative strategies:

 1. Could the method used in the 0.5.x version be revisited, as all of this used to work fine?

 2. Alternatively, how about whenever the page is not scrollable and no scrollable element is active, if j, k, <space>, or <s-space> are pressed, just pass a down-arrow, up-arrow, page-down, or page-up key press through to the page and let the page do whatever it would normally do when receiving one of those key presses?

**Comment by lydell** [comment]
Damn, you seem to be right about tabs being loaded in the background. It seems like no scrollable elements at all are detected if a tab is loaded in the background, regardless of which site it is. I can't believe that I haven't noticed this before (I've used the development version in my main Firefox profiles the whole year). This is a pretty bad bug.

To answer your questions:

1. The 0.5.x scrolling was not perfect either:

   - It didn't support counts well: #399.
   - It worked as if you had placed the mouse pointer in the middle of the viewport and then scrolled. This means that if you were scrolling through a blog post with lots of code snippets in them, where each code snippet has its own scrollbar, you'd often "get stuck" scrolling those code snippets instead of the entire page. This regularly annoyed me.
   - It does not support scrolling a specific target. I often want to target a smaller scrollable element, using `zf`, and be able to scroll that element using VimFx's keys. See #11.

> One other thing I notice -- when hitting j/k on Google Groups, the whole page does bump up and down a couple pixels, as if the page is slightly larger than the viewport.

Thanks for spotting this. That is a case not covered yet: When the entire page appears to scrollable,  but hasn't got a scrollbar (due to "bad" CSS on the page).

2. There is no such thing as _just_ "passing" another key press to the page. I've experimented a lot with it, and it is really complicated. (Prove me wrong!)

   Also, Firefox's native scrolling using `<space>` or the arrow keys isn't perfect either. When using them,  I often find myself having to click on the page to get them scroll the correct element, or scroll at all.

**Comment by lydell** [comment]
I now understand why I haven't noticed this before: This has not always been the case.

For a time I feared the the 'overflow' events (which we use to discover scrollable elements) do not fire in background tabs. I just checked, though: They do. Phew.

The problem is that we throw away all the scrollable elements that we found in the background tab when switching to it. That's the problem. Should be easy to fix.

Thanks for your report and your rigorous testing! :+1:

**Comment by abastardi** [comment]
>> One other thing I notice -- when hitting j/k on Google Groups, the whole page does bump up and down a couple pixels, as if the page is slightly larger than the viewport.

> Thanks for spotting this. That is a case not covered yet: When the entire page appears to scrollable, but hasn't got a scrollbar (due to "bad" CSS on the page).

Is that fixable? Do you want to track that in a separate issue?

For what it's worth, scrolling in Google Groups is also broken in Vimium on Chrome.

> There is no such thing as just "passing" another key press to the page. I've experimented a lot with it, and it is really complicated. (Prove me wrong!)

After suggesting that, I started to investigate, and I think you're right.

**Comment by lydell** [comment]
> > Thanks for spotting this. That is a case not covered yet: When the entire page appears to scrollable, but hasn't got a scrollbar (due to "bad" CSS on the page).
> 
> Is that fixable? Do you want to track that in a separate issue?

Yes, it should be fixable. No need to open a separate issue this time.

**Comment by lydell** [comment]
> One other thing I notice -- when hitting j/k on Google Groups, the whole page does bump up and down a couple pixels, as if the page is slightly larger than the viewport.

That should be fixed in master now.

Continuing with the other issues…

**Comment by lydell** [comment]
I think I’ve addressed everything in this issue now. All commits are in master. Keeping this open until somebody can confirm.

**Comment by lydell** [comment]
After testing master out for a bit in my main profile, I noticed that `TypeError: can't access dead object` errors are thrown when trying to scroll sometimes on gmail. I suspect this is due to `<iframe>`s (which are used on gmail).

**Comment by lydell** [comment]
^ Fixed.

**Comment by lydell** [comment]
@abastardi I've just released versuon 0.7.0. Could you try it out and report back how it works for you?

**Comment by abastardi** [comment]
Gmail seems to be working fine now. There is still a problem in Google Groups -- depending on the system DPI scaling setting and/or zoom level in Firefox, VimFX still thinks the whole page is scrollable (hitting j/k bumps the page up and down a pixel rather than scrolling the central scroll area).

I have my system DPI scaling set to 150%. If I zoom out to 67% (which is equivalent to 100% DPI scaling), then Google Groups will scroll, but not at any zoom level higher than that. I know my DPI scaling is a bit high, but the Windows default for HD monitors is 125%, and even at that level, scrolling won't work on Google Groups. 100% DPI scaling results in very small text on an HD monitor.

Thanks.

**Comment by lydell** [comment]
Thanks for confirming!

I'll look into the DPI related issue.

At least you can use `f` and `zf` to target the scrollable area on Google Groups now, can't you? I mean, as a workaround for the time being.

**Comment by abastardi** [comment]
Yes, using `f` to target the scrollable area works fine for now as a workaround.

**Comment by lydell** [comment]
@abastardi Please try out 0.7.1 and see if it helps.

**Comment by abastardi** [comment]
Yes, scrolling works in Google Groups now. Thanks a lot for your persistence in getting this right. Awesome work!
